### ISSUE TITLE
Error: File '/node_modules/detectincognitojs/dist/detectIncognito.d.ts' is not a module.ts(2306)

### ISSUE THREAD

**Issue by michaelkolesidis** [Joe12387/detectIncognito#29]
I install the package, I follow the instructions and I try to import it

    import { detectIncognito } from "detectincognitojs";

And I get an error:

    File '/node_modules/detectincognitojs/dist/detectIncognito.d.ts' is not a module.ts(2306)

I am using create-react-app with the TypeScript template

I have also created a minimal reproducible example, an empty test project and when I tried to import it, I had the exact same problem.

The previous version (1.1.2) works fine, the error only occurs in the latest version (1.2.0).

**Version**: 1.2.0
**Browsers**: All

**Comment by RolginRoman** [comment]
Same here

Got these error with TS 4.9.5 and node 18

**Comment by Joe12387** [comment]
1.2.1 pushed. Can someone confirm that this has been resolved?

**Comment by michaelkolesidis** [comment]
Thanks for the fast response, will check it first thing in the morning

**Comment by benferns** [comment]
Unfortunately this still occurs for me in 1.2.1, using a relatively default esbuild setup with typescript.

**Comment by RolginRoman** [comment]
Hi @Joe12387 
Thanks for the blazing fast response 👍 

Just checked it and I am still getting the same error
I prepared tiny repro https://stackblitz.com/edit/typescript-exiruy?file=index.ts

Error's seen there - 
> File 'stackblitz:/node_modules/detectincognitojs/dist/detectIncognito.d.ts' is not a module.(2306)

**Comment by michaelkolesidis** [comment]
I also getting the same error.

**Comment by Joe12387** [comment]
1.3.0 pushed, did it work?

**Comment by michaelkolesidis** [comment]
Yes, now it worked perfectly!

Thanks once again for the prompt reply ❤️
